# -*- coding: utf-8 -*-
"""23DTSA55_shahawaj pasha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pK_miCRKv5n03GAAR8nULwwKYtlAWWe
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, roc_auc_score

from sklearn.ensemble import RandomForestClassifier

train_trans = pd.read_csv("train_transaction.csv")
train_id = pd.read_csv("train_identity.csv")

data = train_trans.merge(train_id, on="TransactionID", how="left")

data.shape

data.head()

data.info()

missing_percentage = data.isnull().mean().sort_values(ascending=False)
missing_percentage.head(10)

for col in data.columns:
    if data[col].dtype == 'object':
        data[col].fillna("Unknown", inplace=True)
    else:
        data[col].fillna(data[col].median(), inplace=True)

le = LabelEncoder()

for col in data.select_dtypes(include='object').columns:
    data[col] = le.fit_transform(data[col])

X = data.drop("isFraud", axis=1)
y = data["isFraud"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

sns.countplot(x=y)
plt.title("Fraud vs Non-Fraud Distribution")
plt.show()

sns.boxplot(x='isFraud', y='TransactionAmt', data=data)
plt.title("Transaction Amount vs Fraud")
plt.show()

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(pd.Series(y_train_res).value_counts())

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    class_weight='balanced',
    random_state=42
)

rf.fit(X_train_res, y_train_res)

rf_preds = rf.predict(X_test)
rf_probs = rf.predict_proba(X_test)[:, 1]

print(classification_report(y_test, rf_preds))
print("ROC-AUC Score:", roc_auc_score(y_test, rf_probs))

feature_importance = pd.Series(
    rf.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

feature_importance.head(10)

!pip install xgboost
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=10,
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train_res, y_train_res)

xgb_preds = xgb.predict(X_test)
xgb_probs = xgb.predict_proba(X_test)[:, 1]

print(classification_report(y_test, xgb_preds))
print("ROC-AUC Score:", roc_auc_score(y_test, xgb_probs))

results = pd.DataFrame({
    "Model": ["Random Forest", "XGBoost"],
    "ROC-AUC": [
        roc_auc_score(y_test, rf_probs),
        roc_auc_score(y_test, xgb_probs)
    ]
})

results

xgb_importance = pd.Series(
    xgb.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

xgb_importance.head(10)

from sklearn.metrics import roc_curve

fpr_rf, tpr_rf, _ = roc_curve(y_test, rf_probs)
fpr_xgb, tpr_xgb, _ = roc_curve(y_test, xgb_probs)

plt.figure(figsize=(8,6))
plt.plot(fpr_rf, tpr_rf, label="Random Forest")
plt.plot(fpr_xgb, tpr_xgb, label="XGBoost")
plt.plot([0,1], [0,1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.show()

"""## ***XGBoost outperforms Random Forest with a higher ROC-AUC and recall score. Since fraud detection prioritizes identifying fraudulent transactions even at the cost of some false positives, XGBoost is better suited for this problem.***

## ***✔ False Positives***

**Legitimate customers blocked**

**Poor user experience**

## ***✔ False Negatives***

**Fraud goes undetected**

**Financial and reputational loss**

## ***✔ Ethical Challenge***

**Bias in training data may unfairly flag specific groups. Continuous auditing and transparency are essential before deployment.**
"""

sample = pd.read_csv("sample_submission.csv")
sample.head()

from google.colab import files
files.download("sample_submission.csv")

!ls

import pandas as pd

# Load test files
test_trans = pd.read_csv("test_transaction.csv")
test_id = pd.read_csv("test_identity.csv")

# Merge
test_data = test_trans.merge(test_id, on="TransactionID", how="left")

# Handle missing values
for col in test_data.columns:
    if test_data[col].dtype == 'object':
        test_data[col] = test_data[col].fillna("Unknown")
    else:
        test_data[col] = test_data[col].fillna(test_data[col].median())

# Encode categorical columns
for col in test_data.select_dtypes(include='object').columns:
    test_data[col] = test_data[col].astype('category').cat.codes

xgb.feature_names_in_

# 1. Add missing columns
for col in xgb.feature_names_in_:
    if col not in test_data.columns:
        test_data[col] = 0

# 2. Drop extra columns
test_data = test_data[xgb.feature_names_in_]

test_preds = xgb.predict_proba(test_data)[:, 1]

submission = pd.DataFrame({
    "TransactionID": test_trans["TransactionID"],
    "isFraud": test_preds
})

submission.to_csv("submission.csv", index=False)

from google.colab import files
files.download("submission.csv")

